### ISSUE TITLE
Split the logic and the data

### ISSUE THREAD

**Issue by GabLeRoux** [kimlavoie/fakeDB#1]
You seem to have lots of commands out there in a single js file, this should be separated ;)

Did you consider using something like this?  https://www.json-generator.com/

:v:

**Comment by kimlavoie** [comment]
Agreed, but it's for a small project with our students, it won't get much bigger than this and it should be in a single file so it's simple to import.
Thank you for your input.

...

(Je me sens stalké haha)

**Comment by GabLeRoux** [comment]
eheh, je voulais te troller un peu ce matin. Bonne journée :P
